[accessibility]
ui_scale = 1.20

[bar.default]
center = [ "workspaces", "spacer_1", "active_window" ]
concave_edge_corners = true
end = [ "media", "spacer_1", "tray", "notifications", "network", "volume", "session" ]
font_family = "Inconsolata Nerd Font Mono"
margin_edge = 0
margin_ends = 0
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 0
radius_top_right = 0
scale = 1.10
start = [ "launcher", "clock", "spacer_1", "group:g1" ]
thickness = 35

    [[bar.default.capsule_group]]
    border = ""
    fill = "on_secondary"
    id = "g1"
    members = [ "temp", "sysmon_2", "sysmon_3" ]
    opacity = 1.0
    padding = 6.0

[dock]
enabled = true
reserve_space = false
show_dots = true
smart_auto_hide = true

[plugins]
enabled = [ "noctalia/bitwarden" ]

[shell]
clipboard_image_action_command = "satty -f -"
font_family = "Inconsolata Nerd Font Mono"
launch_apps_as_systemd_services = true
password_style = "random"
polkit_agent = true
settings_show_advanced = true

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher.providers.session]
    global = true

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"

    [shell.screenshot]
    copy_to_clipboard = false
    directory = "$HOME/Pictures/Screenshots"
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Tokyo-Night"
community_palette = "Vesper"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "kcolorscheme", "qt" ]

[wallpaper.default]
path = "/home/mikec/Pictures/Wallpapers/Dueling Planets.jpg"

[widget.clock]
color = "secondary"
format = "{:%H:%M %A %m/%d/%y}"

[widget.launcher]
color = "secondary"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
color = "secondary"

[widget.notifications]
color = "secondary"

[widget.session]
color = "error"

[widget.spacer_1]
type = "spacer"

[widget.temp]
show_value = false

[widget.sysmon_2]
glyph = "gpu-usage"
show_value = false
stat = "gpu_temp"
type = "sysmon"

[widget.sysmon_3]
glyph = "cpu-2"
stat = "ram_used"
type = "sysmon"

[widget.tray]
capsule = true
capsule_fill = "on_secondary"

[widget.volume]
color = "secondary"

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_fill = "on_primary"
inactive_pill_size = 1.0
max_label_chars = 20
pill_scale = 1.0
show_labels = true
