config_version = 13

[bar.default]
font_family = "Inconsolata Nerd Font Mono"

[dock]
enabled = true
reserve_space = false
show_dots = true
smart_auto_hide = true

[plugins]
enabled = [ "noctalia/bitwarden" ]

[shell]
font_family = "Inconsolata Nerd Font Mono"
password_style = "random"

[shell.greeter_sync]
auto_sync = false

[shell.launcher.providers.session]
global = true

[shell.panel]
wallpaper_placement = "floating"

[shell.screenshot]
directory = "$HOME/Pictures/Screenshots"

[theme]
builtin = "Tokyo-Night"
community_palette = "Vesper"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

[theme.templates]
builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "kcolorscheme", "qt" ]

[wallpaper.default]
path = "$HOME/Pictures/Wallpapers/Dueling Planets.jpg"

[widget.workspaces]
max_label_chars = 20
pill_scale = 1.0
show_labels = true
