#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config     \
    mouse_follows_focus          off \
    window_placement             second_child \
    window_animation_duration    0.0 \
    window_opacity_duration      0.0 \
    insert_feedback_color        0xaad75f5f  \
    split_ratio                  0.50 \
    split_type                   auto \
    auto_balance                 on \
    mouse_modifier               fn \
    mouse_action1                move \
    mouse_action2                resize \
    mouse_drop_action            swap \
    top_padding                  15 \
    bottom_padding               15 \
    left_padding                 15 \
    right_padding                15 \
    window_gap                   15

echo "yabai configuration loaded.."
borders

