-- Hyprland Config

require("config.animations")
require("config.autostart")
require("config.colors")
require("config.decorations")
require("config.variables")
require("config.utility")
require("config.environment")
require("config.inputs")
require("config.misc")
require("config.monitors")
require("config.binds")
require("config.windowrules")
require("config.workspaces")
