-- Cachy colors

CACHYLGREEN = "rgba(82dcccff)"
CACHYMGREEN = "rgba(00aa84ff)"
CACHYDGREEN = "rgba(007d6fff)"
CACHYLBLUE = "rgba(01ccffff)"
CACHYMBLUE = "rgba(182545ff)"
CACHYDBLUE = "rgba(111826ff)"
CACHYWHITE = "rgba(ffffffff)"
CACHYGREY = "rgba(ddddddff)"
CACHYGRAY = "rgba(798bb2ff)"

-- Noctalia community Vesper palette
-- dark variant

ND_PRIMARY = "rgba(ffc799ff)"
ND_ONPRIMARY = "rgba(000000ff)"
ND_SECONDARY = "rgba(99ffe4ff)"
ND_ONSECONDARY = "rgba(000000ff)"
ND_TERTIARY = "rgba(fbadffff)"
ND_ONTERTIARY = "rgba(000000ff)"
ND_ERROR = "rgba(ff8080ff)"
ND_ONERROR = "rgba(000000ff)"
ND_SURFACE = "rgba(0c0c0cff)"
ND_ONSURFACE = "rgba(ffffffff)"
ND_SURFACEVARIANT = "rgba(1c1c1cff)"
ND_ONSURFACEVARIANT = "rgba(a0a0a0ff)"
ND_OUTLINE = "rgba(505050ff)"
ND_OUTLINEDIM = "rgba(1c1c1cff)"
ND_SHADOW = "rgba(000000ff)"
ND_HOVER = "rgba(282828ff)"
ND_ONHOVER = "rgba(ffffffff)"

ND_TERM_FG = "rgba(ffffffff)"
ND_TERM_BG = "rgba(0c0c0cff)"
ND_TERM_BLACK = "rgba(0c0c0cff)"
ND_TERM_RED = "rgba(ff8080ff)"
ND_TERM_GREEN = "rgba(99ffe4ff)"
ND_TERM_YELLOW = "rgba(ffc799ff)"
ND_TERM_BLUE = "rgba(80b3ffff)"
ND_TERM_MAGENTA = "rgba(fbadffff)"
ND_TERM_CYAN = "rgba(99ffe4ff)"
ND_TERM_WHITE = "rgba(a0a0a0ff)"
ND_TERM_BBLACK = "rgba(505050ff)"
ND_TERM_BRED = "rgba(ff8080ff)"
ND_TERM_BGREEN = "rgba(99ffe4ff)"
ND_TERM_BYELLOW = "rgba(ffc799ff)"
ND_TERM_BBLUE = "rgba(80b3ffff)"
ND_TERM_BMAGENTA = "rgba(fbadffff)"
ND_TERM_BCYAN = "rgba(99ffe4ff)"
ND_TERM_BWHITE = "rgba(ffffffff)"
ND_TERM_CURSOR = "rgba(ffffffff)"
ND_TERM_CURSORTEXT = "rgba(000000ff)"
ND_TERM_SELFG = "rgba(000000ff)"
ND_TERM_SELBG = "rgba(ffc799ff)"
