return {
  -- 'nvim-tree/nvim-tree.lua',
  -- version = '*',
  -- lazy = true,
  -- event = 'BufEnter',
  -- dependencies = {
  --   'nvim-tree/nvim-web-devicons',
  -- },
  -- config = function()
  --   local HEIGHT_RATIO = 0.8
  --   local WIDTH_RATIO = 0.8
  --
  --   require('nvim-tree').setup {
  --     filters = {
  --       dotfiles = true,
  --     },
  --     view = {
  --       relativenumber = true,
  --       signcolumn = 'yes',
  --       float = {
  --         enable = true,
  --         quit_on_focus_loss = true,
  --         open_win_config = function()
  --           local screen_w = vim.opt.columns:get()
  --           local screen_h = vim.opt.lines:get() - vim.opt.cmdheight:get()
  --           local window_w = screen_w * WIDTH_RATIO
  --           local window_h = screen_h * HEIGHT_RATIO
  --           local window_w_int = math.floor(window_w)
  --           local window_h_int = math.floor(window_h)
  --           local center_x = (screen_w - window_w) / 2
  --           local center_y = ((vim.opt.lines:get() - window_h) / 2) - vim.opt.cmdheight:get()
  --           return {
  --             border = 'rounded',
  --             relative = 'editor',
  --             row = center_y,
  --             col = center_x,
  --             width = window_w_int,
  --             height = window_h_int,
  --           }
  --         end,
  --       },
  --       width = function()
  --         return math.floor(vim.opt.columns:get() * WIDTH_RATIO)
  --       end,
  --     },
  --     renderer = {
  --       icons = {
  --         git_placement = 'signcolumn',
  --         glyphs = {
  --           default = ' ',
  --           symlink = ' ',
  --           git = {
  --             untracked = ' ',
  --           },
  --         },
  --         show = {
  --           git = true,
  --           folder = true,
  --           file = true,
  --           folder_arrow = false,
  --         },
  --       },
  --     },
  --     update_focused_file = {
  --       enable = true,
  --     },
  --     sync_root_with_cwd = true,
  --     disable_netrw = true,
  --     hijack_netrw = true,
  --   }
  --   vim.keymap.set('n', '<leader>e', ':NvimTreeToggle<CR>', { desc = 'Toggle file explorer', silent = true })
  -- end,
}
