return {
  -- {
  --   'ryanmsnyder/toggleterm-manager.nvim',
  --   dependencies = {
  --     'akinsho/nvim-toggleterm.lua',
  --     'nvim-telescope/telescope.nvim',
  --     'nvim-lua/plenary.nvim',
  --   },
  --   config = function()
  --     local actions = require('toggleterm-manager').actions
  --     require('toggleterm-manager').setup {
  --       mappings = {
  --         i = {
  --           ['<CR>'] = { action = actions.toggle_term, exit_on_action = true },
  --           ['<C-i>'] = { action = actions.create_term, exit_on_action = false },
  --           ['<C-d>'] = { action = actions.delete_term, exit_on_action = false },
  --           ['<C-r>'] = { action = actions.rename_term, exit_on_action = false },
  --         },
  --       },
  --     }
  --   end,
  -- },
}
