return {
  --   -- keeping this here in case i find something weird with vtsls as backup
  --   {
  --     'pmizio/typescript-tools.nvim',
  --     dependencies = { 'nvim-lua/plenary.nvim', 'neovim/nvim-lspconfig' },
  --     opts = {
  --       on_attach = function(client)
  --         client.server_capabilities.documentFormattingProvider = false
  --         client.server_capabilities.documentRangeFormattingProvider = false
  --       end,
  --       settings = {
  --         expose_as_code_action = 'all',
  --         tsserver_plugins = {
  --           '@styled/typescript-styled-plugin',
  --         },
  --         complete_function_calls = true,
  --         jsx_close_tag = {
  --           enable = true,
  --           filetypes = { 'javascriptreact', 'typescriptreact' },
  --         },
  --       },
  --     },
  --   },
}
